services:
  store_manager_cli:
    build: .
    container_name: store_manager_cli
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mongo
    stdin_open: true
    tty: true  
    networks:
      - labo01-network

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: labo01
      MYSQL_DATABASE: labo01_db
      MYSQL_USER: labo01
      MYSQL_PASSWORD: labo01
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - labo01-network

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: labo01
      MONGO_INITDB_ROOT_PASSWORD: labo01
    volumes:
      - mongo-data:/data/db
    networks:
      - labo01-network

networks:
  labo01-network:
    external: true

volumes:
  mongo-data: